import asyncio
import random
import time
from dataclasses import dataclass, field
from backend.mbti.types import TraitProfile
from backend.mbti.personas import PERSONA_DEFINITIONS


@dataclass
class Observation:
    """Raw perceptual input — a price move, a conversation line, a market event."""
    content: str
    category: str  # "price", "news", "conversation", "reflection"
    importance: float  # 0.0–1.0
    tick: int
    timestamp: float = field(default_factory=time.time)


@dataclass
class Reflection:
    """A higher-level thought generated by chewing on recent observations."""
    content: str
    confidence: float
    source_observations: list[int]  # indices into observation list
    tick: int


class AgentMemory:
    def __init__(self, agent_id: str, traits: TraitProfile):
        self.agent_id = agent_id
        self.traits = traits
        self.observations: list[Observation] = []
        self.reflections: list[Reflection] = []
        self._last_reflection_tick = -1
        # Sentiment tracking per symbol
        self.symbol_sentiment: dict[str, float] = {}  # -1.0 to +1.0

    def observe(self, content: str, category: str, importance: float, tick: int):
        obs = Observation(
            content=content,
            category=category,
            importance=min(1.0, max(0.0, importance)),
            tick=tick,
        )
        self.observations.append(obs)
        # Prune old observations (keep most recent 60)
        if len(self.observations) > 60:
            self.observations = self.observations[-60:]

    def reflect(self, tick: int, prices: dict[str, float], changes: dict[str, float]) -> list[Reflection]:
        """Generate reflections from recent un-reflected observations. Returns new reflections."""
        new_reflections: list[Reflection] = []
        recent_unreflected = [
            (i, obs) for i, obs in enumerate(self.observations)
            if obs.tick > self._last_reflection_tick and obs.importance > 0.3
        ]

        if not recent_unreflected:
            return new_reflections

        self._last_reflection_tick = tick
        grouped: dict[str, list[Observation]] = {}
        for _, obs in recent_unreflected:
            grouped.setdefault(obs.category, []).append(obs)

        # Try LLM first for a richer reflection
        llm_content = None
        try:
            from backend.engine.llm_client import llm_available, generate_reflection
            if llm_available():
                defn = PERSONA_DEFINITIONS.get(self.agent_id, {})
                obs_texts = [o.content for o in recent_unreflected]
                llm_content = asyncio.get_event_loop().run_until_complete(
                    generate_reflection(
                        self.agent_id, defn.get("name", self.agent_id),
                        defn.get("backstory", ""), defn.get("motto", ""),
                        obs_texts, prices, tick,
                    )
                )
        except Exception:
            pass

        if llm_content:
            content = llm_content
            confidence = 0.6 + 0.2 * self.traits.thinking
        else:
            # Fall back to rule-based
            price_obs = grouped.get("price", [])
            conv_obs = grouped.get("conversation", [])
            if len(price_obs) >= 3:
                content = self._generate_price_reflection(price_obs, prices, changes)
            elif len(conv_obs) >= 2:
                content = self._generate_conversation_reflection(conv_obs)
            else:
                content = "Hmm, nothing notable happening."
            confidence = 0.3 + 0.3 * self.traits.thinking

        ref = Reflection(
            content=content,
            confidence=confidence,
            source_observations=[i for i, _ in recent_unreflected],
            tick=tick,
        )
        new_reflections.append(ref)

        for r in new_reflections:
            self.reflections.append(r)
            # Prune old reflections
            if len(self.reflections) > 30:
                self.reflections = self.reflections[-30:]

        return new_reflections

    def _generate_price_reflection(
        self, obs: list[Observation], prices: dict[str, float], changes: dict[str, float]
    ) -> str:
        up_count = sum(1 for o in obs if "up" in o.content.lower() or "rise" in o.content.lower())
        down_count = sum(1 for o in obs if "down" in o.content.lower() or "drop" in o.content.lower())
        total = up_count + down_count or 1
        bullish_pct = up_count / total

        is_contrarian = (1 - self.traits.extraversion) > 0.5  # introverts tend contrarian
        if is_contrarian:
            bullish_pct = 1 - bullish_pct

        if bullish_pct > 0.7:
            return random.choice([
                "The market feels strong. Momentum is on our side.",
                "Bullish signals everywhere. Time to ride the wave.",
                "The trend is clear — upward movement ahead.",
            ])
        elif bullish_pct < 0.3:
            return random.choice([
                "Dark clouds gathering. Better be cautious.",
                "The bears are taking control. Defensive positions needed.",
                "Too many red flags to ignore. Reducing exposure makes sense.",
            ])
        else:
            return random.choice([
                "Mixed signals. Staying flexible is key.",
                "The market can't decide. Patience is warranted.",
                "Uncertainty rules. Wait for clearer direction.",
            ])

    def _generate_conversation_reflection(self, obs: list[Observation]) -> str:
        others = set()
        for o in obs:
            for word in o.content.split():
                word = word.rstrip(":,;.!\"").rstrip("]") + "]"
                if word.startswith("[") and word.endswith("]"):
                    others.add(word)
        if others:
            names = ", ".join(others)
            return random.choice([
                f"Talked with {names}. Their views are worth considering.",
                f"Interesting perspectives from {names}. Adjusting my outlook.",
                f"The conversation with {names} confirmed some of my doubts.",
            ])
        return "Market chatter is noisy. I'll trust my own analysis."

    def recent_thoughts(self, n: int = 10) -> list[str]:
        """Return most recent reflections and important observations as text lines."""
        items: list[tuple[int, str]] = []
        for r in self.reflections[-n:]:
            items.append((r.tick, f"[THINK] {r.content}"))
        for o in self.observations[-n:]:
            if o.importance > 0.5:
                prefix = {"price": "[PRICE]", "news": "[NEWS]", "conversation": "[CHAT]", "reflection": "[THINK]"}.get(o.category, "[*]")
                items.append((o.tick, f"[{o.category}] {o.content}"))
        items.sort(key=lambda x: x[0])
        return [text for _, text in items[-n:]]

    def get_sentiment(self) -> float:
        """Overall sentiment derived from recent reflections and observations."""
        if not self.reflections and not self.observations:
            return 0.0
        score = 0.0
        for r in self.reflections[-5:]:
            if any(w in r.content.lower() for w in ["bull", "strong", "rise", "upward", "moon"]):
                score += r.confidence
            elif any(w in r.content.lower() for w in ["bear", "dark", "drop", "cautious", "red"]):
                score -= r.confidence
        for o in self.observations[-10:]:
            if o.category == "price":
                if any(w in o.content.lower() for w in ["up", "rise", "gain", "bull"]):
                    score += o.importance * 0.3
                elif any(w in o.content.lower() for w in ["down", "drop", "loss", "bear"]):
                    score -= o.importance * 0.3
        return max(-1.0, min(1.0, score))
