INITIAL_CASH = 10_000.0
SYMBOLS = ["AAPL", "GOOGL", "MSFT", "TSLA", "AMZN"]
TICK_INTERVAL_SEC = 2.0
MARKET_POLL_SEC = 30.0
MAX_PRICE_HISTORY = 300
STRICT_MATCHING = False
BUY_THRESHOLD = 0.15
SELL_THRESHOLD = -0.10
HOUSE_ABSORB_MIN_SHARES = 1

# Town simulation
CONVERSATION_RADIUS = 4
REFLECTION_EVERY_N_TICKS = 5
OBSERVATION_MAX = 60
REFLECTION_MAX = 30
